[package]
name = "project-name"
version = "0.1.0"
edition = "2024"
description = "Add your description here"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/conjikidow/repo"
publish = false

[dependencies]
